### ISSUE TITLE
Errors while trying "make"

### ISSUE THREAD

**Issue by ted051** [pavel-demin/DiscoRedTRX#1]
Hello Pavel,
after the second try : The Readme file is not complete.
I had to add the following:

```
apt-get install python-serial
apt-get install make
apt-get install python-alsaaudio
apt-get install libasound2-dev
```

The last two installs were optional, because i wanted to try alsamixer for volume control.
1. Problem: errors "import colors" fails in the "make" command.
   2.Problem: after trying "python main.py" the following error occur:
   ..Import error: No module red_pitayaa_emb

What have I done wrong??
Best regards Wolfgang, DH1AKF

**Comment by ted051** [comment]
I forgot: In the "make" command :+1: 
3- times "import colors" fails.

**Comment by pavel-demin** [comment]
Hello Wolfgang,

Thank you for your tests.

I've fixed the commands in README and the names of the ALSA mixers in main.py.

Could you give the new version a try?

Best regards,

Pavel

**Comment by ted051** [comment]
Hello Pavel,
thanks for the correction, but now comes another error:

```
root@red-pitaya:~/DiscoRedTRX-master# python main.py
Traceback (most recent call last):
  File "main.py", line 19, in <module>
    playback = alsaaudio.Mixer('Speaker')
alsaaudio.ALSAAudioError: No such file or directory
```

Best regards, Wolfgang

**Comment by ted051** [comment]
Hello Pavel,
thanks for the correction, but now comes another error:

root@red-pitaya:~/DiscoRedTRX-master# python main.py
Traceback (most recent call last):
File "main.py", line 19, in 
playback = alsaaudio.Mixer('Speaker')
alsaaudio.ALSAAudioError: No such file or directory

Best regards, Wolfgang

**Comment by pavel-demin** [comment]
Hello Wolfgang,

Do you have a USB sound card plugged into your Red Pitaya?

You can find the correct names of the ALSA mixers by running the alsamixer command. The names of the mixers are shown at the bottom of the alsamixer screen.

Then, you can replace Speaker and Mic in main.py with the correct names corresponding to your USB sound card.

Best regards,

Pavel

**Comment by ted051** [comment]
Hello Pavel, with connected USB- Headset I had at last success!
But the volume control (slider from stm32f7) doesn't work.
Best regards, Wolfgang

**Comment by ted051** [comment]
Hello Pavel, with connected USB- Headset I had at last success!

But the volume control (slider from stm32f7) doesn't work.

Best regards, Wolfgang

 

Von: Pavel Demin [mailto:notifications@github.com] 
Gesendet: Sonntag, 24. April 2016 13:19
An: pavel-demin/DiscoRedTRX
Cc: ted051; Author
Betreff: Re: [pavel-demin/DiscoRedTRX] Errors while trying "make" (#1)

 

Hello Wolfgang,

Do you have a USB sound card plugged into your Red Pitaya?

You can find the correct names of the ALSA mixers by running the alsamixer command. The names of the mixers are show at the bottom of the alsamixer screen.

Then, you can replace Speaker and Mic in main.py with the correct names corresponding to your USB sound card.

Best regards,

Pavel

**Comment by pavel-demin** [comment]
The commands that main.py expects should look like the following:
- `P0, P1, ..., P9` for the Speaker volume
- `R0, R1, ..., R9` for the Mic volume

Anyway, all the commands should be changed to a fixed length binary format to simplify the transmission of the RX level values back to the Discovery board.

**Comment by pavel-demin** [comment]
Volume control and make work well in the latest version.
